version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: /var/www/scripts/stopScout.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /var/www/scripts/startScout.sh
      timeout: 300
      runas: root
